language: cpp
dist: bionic

compiler:
  - clang
  - gcc

os:
  - linux

before_install:
  - sudo apt update -qq

install:
  - sudo apt install -y build-essential cmake libssl-dev libboost-all-dev python-dev
  - wget https://github.com/boostorg/beast/archive/v124.tar.gz
  - tar -xf v124.tar.gz
  - cd beast-124/
  - sudo cp -r include/boost/ /usr/include/
  - cd ..

script:
  - ./build.sh
  - cd build
  - ctest --output-on-failure
